package addressbook;

/**
 *
 * @author RJ
 */
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;

public class Register extends javax.swing.JFrame {
    Connection con;
    DbUtil dbUtil;

    /**
     * Creates new form register
     */
    public Register() {
        initComponents();
        
        dbUtil = new DbUtil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Arial", Font.PLAIN, 13));
        TFUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Arial", Font.PLAIN, 13));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Arial", Font.PLAIN, 13));
        TFConfirmPassword = new javax.swing.JPasswordField();
        TFPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Arial", Font.PLAIN, 13));
        pinCode = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();

        setResizable(false);

        jLabel1.setFont(new Font("Yu Gothic Light", Font.PLAIN, 34)); // NOI18N
        jLabel1.setText("Sign Up");

        jLabel2.setText("User Name");

        TFUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFUserNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        jLabel4.setText("Confirm Password");

        TFConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFConfirmPasswordActionPerformed(evt);
            }
        });

        TFPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPasswordActionPerformed(evt);
            }
        });

        jLabel5.setText("Pin Code");

        btnRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(0, 309, Short.MAX_VALUE)
        			.addComponent(btnRegister, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
        			.addGap(49))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4)
        				.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        					.addComponent(pinCode, Alignment.LEADING)
        					.addComponent(TFConfirmPassword, Alignment.LEADING)
        					.addComponent(TFUserName, Alignment.LEADING)
        					.addComponent(TFPassword, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
        				.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(188, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        			.addGap(41)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(TFUserName, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(TFPassword, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        			.addGap(11)
        			.addComponent(jLabel4)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(TFConfirmPassword, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel5)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(pinCode, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnRegister, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        			.addGap(20))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFUserNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFUserNameActionPerformed

    private void TFConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFConfirmPasswordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFConfirmPasswordActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    	
    	
    	
    	String username = TFUserName.getText();
        String password = String.valueOf(TFPassword.getPassword());
        String pincode = pinCode.getText();
        String cpassword = String.valueOf(TFConfirmPassword.getPassword());
        
        int n = password.compareTo(cpassword);
        
        
        if (n==0)
        {
        	
        
        String query="insert into UsernamesPasswords (username,password,pincode) values(?,?,?);";
       
        con=dbUtil.getConnection();
        PreparedStatement preparedStatement = null;
        try{
            
            preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, username);
            preparedStatement.setString(2, password);
            preparedStatement.setString(3, pincode);
            
            
            preparedStatement.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "record inserted successfully ","Info",JOptionPane.INFORMATION_MESSAGE);
            
            preparedStatement.close();
        }catch(SQLException | HeadlessException e){
             
            JOptionPane.showMessageDialog(null, "record not inserted successfully due to " + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }finally{
            dbUtil.closeConnection();
        }
        
        }
        else 
        {
        	JOptionPane.showMessageDialog(null, "Passwords do not match!\nPlease Try Again! ");
        }
        TFUserName.setText("");
        TFConfirmPassword.setText("");
        TFPassword.setText("");
        pinCode.setText("");
        
        
      
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void TFPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TFConfirmPassword;
    private javax.swing.JPasswordField TFPassword;
    private javax.swing.JTextField TFUserName;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pinCode;
    // End of variables declaration//GEN-END:variables
}