package addressbook;

/**
 *
 * @author RJ
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import java.awt.Font;
import java.awt.Image;

import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.SwingConstants;
import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class UserLogin extends javax.swing.JFrame {
    Register obj=new Register();
    ForgotPassword fp=new ForgotPassword();
    DbUtil dbUtil=null; 
    ViewAddressBook viewAdressBook;
    

    /**
     * Creates new form userLogin
     */
    public UserLogin() {
        initComponents();
        dbUtil =new DbUtil();
    }

    public  int authentication (String username,String password){
        int user_id=-1;
        String query = "select user_id  from usernamespasswords where username=? and password=?;";
        Connection con= dbUtil.getConnection();
        try (PreparedStatement preparedStatement = con.prepareStatement(query)) {
            preparedStatement.setString(1, username);
            preparedStatement.setString(2, password);
            
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while(resultSet.next()){
                    user_id = resultSet.getInt("user_id");
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            dbUtil.closeConnection();
        }
        
        
        return user_id;
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Arial", Font.BOLD, 14));
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        TFUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Arial", Font.BOLD, 14));
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        btnSignIn = new javax.swing.JButton();
        btnForgetPassword = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        tfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new Font("Yu Gothic Light", Font.PLAIN, 34)); // NOI18N
        jLabel1.setText(" User Login");

        jLabel2.setText("User Name");

        TFUserName.addActionListener((java.awt.event.ActionEvent evt) -> {
            TFUserNameActionPerformed(evt);
        });

        jLabel3.setText("Password");

        btnSignIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnSignInActionPerformed(evt);
        });

        btnForgetPassword.setText("Forgot Password");
        btnForgetPassword.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnForgetPasswordActionPerformed(evt);
        });

        btnSignUp.setText("Sign up");
        btnSignUp.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnSignUpActionPerformed(evt);
        });
        
        JLabel label = new JLabel("");
        Image img = new ImageIcon(this.getClass().getResource("/resources/Questionmark-icon.png")).getImage();
        label.setIcon(new ImageIcon(img));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        				.addComponent(TFUserName, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        				.addComponent(tfPassword, 416, 416, 416)
        				.addComponent(jLabel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        				.addComponent(jLabel3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
        			.addContainerGap(15, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(256)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(btnSignUp, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        				.addComponent(btnForgetPassword, GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(label, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addGap(30))
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGap(34)
        			.addComponent(btnSignIn, GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        			.addGap(38))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(TFUserName, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(tfPassword, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        			.addGap(20)
        			.addComponent(btnSignIn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(label, 0, 0, Short.MAX_VALUE)
        				.addComponent(btnForgetPassword, GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
        			.addGap(18)
        			.addComponent(btnSignUp, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addGap(21))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        
        int uid = authentication(TFUserName.getText(),String.valueOf(tfPassword.getPassword()));
        if (uid>0){
            viewAdressBook=new ViewAddressBook(uid);
            viewAdressBook.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "invalid user or password", "Error", JOptionPane.ERROR_MESSAGE);
            tfPassword.setText("");
            TFUserName.setText("");
        }
        
        
        
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnForgetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgetPasswordActionPerformed
        // TODO add your handling code here:
        fp.setVisible(true);
        
    }//GEN-LAST:event_btnForgetPasswordActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        obj.setVisible(true);
        
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void TFUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UserLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFUserName;
    private javax.swing.JButton btnForgetPassword;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField tfPassword;
}