package addressbook;

/**
 *
 * @author RJ
 */
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;

import java.awt.Font;
import java.awt.Image;

import javax.swing.SwingConstants;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.Color;

import javax.swing.JLabel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class ViewAddressBook extends javax.swing.JFrame {
    Form form=null;
    Data data=null;
    private int user_id;
    
    /**
     * Creates new form viewAdressbook
     */
    public ViewAddressBook() {
        initComponents();
    }
    
    public ViewAddressBook(int user_id) {
        this();
        this.user_id = user_id;
        form=new Form (user_id);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        btnAdd = new javax.swing.JButton();
        btnAdd.setBackground(Color.LIGHT_GRAY);
        btnDelete = new javax.swing.JButton();
        btnDelete.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        	}
        });
        btnDelete.setForeground(Color.RED);
        btnDelete.setBackground(Color.LIGHT_GRAY);
        btnView = new javax.swing.JButton();
        btnView.setBackground(Color.LIGHT_GRAY);
        btnSearch = new javax.swing.JButton();
        btnSearch.setBackground(Color.LIGHT_GRAY);

        setResizable(false);

        jLabel1.setFont(new Font("Yu Gothic Light", Font.PLAIN, 30)); // NOI18N
        jLabel1.setText("WELCOME TO ADDRESSBOOK");

        btnAdd.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        btnAdd.setText("Add Contact");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        btnDelete.setText("Delete Contact");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        

        btnView.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        btnView.setText("View All");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnSearch.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        
        lblNewLabel = new JLabel("");
        Image img3 = new ImageIcon(this.getClass().getResource("/resources/mcg-icon.png")).getImage();
        lblNewLabel.setIcon(new ImageIcon(img3));
        
        label = new JLabel("");
        Image img1 = new ImageIcon(this.getClass().getResource("/resources/add-icon.png")).getImage();
        label.setIcon(new ImageIcon(img1));
        
        label2 = new JLabel("");
        Image img2 = new ImageIcon(this.getClass().getResource("/resources/contacts-icon.png")).getImage();
        label2.setIcon(new ImageIcon(img2));
        
        label5 = new JLabel("");
        Image img4 = new ImageIcon(this.getClass().getResource("/resources/del-icon.png")).getImage();
        label5.setIcon(new ImageIcon(img4));
        
        booklabel = new JLabel("");
        Image img10 = new ImageIcon(this.getClass().getResource("/resources/book-icon.png")).getImage();
        booklabel.setIcon(new ImageIcon(img10));
        
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        	.addGroup(layout.createSequentialGroup()
        	.addContainerGap()
        	.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        	.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        	.addGroup(layout.createSequentialGroup()
        	.addComponent(booklabel, GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        	.addGap(18)
        	.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        	.addComponent(btnAdd, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnView, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        						.addComponent(btnSearch, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnDelete, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addGap(5)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(label5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
        							.addComponent(label)
        							.addGroup(layout.createSequentialGroup()
        								.addGap(1)
        								.addComponent(label2, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))))))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        			.addGroup(layout.createSequentialGroup()
        					.addGap(34)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(btnView, GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        						.addComponent(label2, GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(btnAdd, GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        						.addComponent(label, GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        						.addComponent(btnSearch, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(18)
        							.addComponent(btnDelete, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(36)
        							.addComponent(label5, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)))
        					.addGap(48))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(booklabel, GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        					.addContainerGap())))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Delete input = new Delete();
    	input.setVisible(true);
        
    }//GEN-LAST:event_btnAddActionPerformed
    
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Form input = new Form();
    	input.setVisible(true);
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    	Search input = new Search();
		input.setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
    	
    	// TODO add your handling code here:
    	Data input = new Data();
		input.setVisible(true);
    }//GEN-LAST:event_btnViewActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAddressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewAddressBook().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private JLabel lblNewLabel;
    private JLabel label;
    private JLabel label2;
    private JLabel label5;
    private JLabel booklabel;
    // End of variables declaration//GEN-END:variables
}